spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
      sql-dialect: org.hibernate.dialect.MySQL5Dialect
